# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"d\n\x0bVoteRequest\x12\x15\n\rcandidateTerm\x18\x01 \x01(\x04\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x04\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x04\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x04\",\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x97\x01\n\rAppendRequest\x12\x12\n\nleaderTerm\x18\x01 \x01(\x04\x12\x10\n\x08leaderId\x18\x02 \x01(\x04\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x04\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x04\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x19\n\x11leaderCommitIndex\x18\x06 \x01(\x04\"/\n\x0e\x41ppendResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x06\n\x04Void\"8\n\x11GetLeaderResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\x04\x12\x13\n\x0bnodeAddress\x18\x02 \x01(\t\" \n\x0eSuspendRequest\x12\x0e\n\x06period\x18\x01 \x01(\x04\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"5\n\x08LogEntry\x12\x1b\n\x08keyValue\x18\x01 \x01(\x0b\x32\t.KeyValue\x12\x0c\n\x04term\x18\x02 \x01(\x04\"!\n\x0eSetValResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"0\n\x0eGetValResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t2\x85\x02\n\x13RaftElectionService\x12*\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\r.VoteResponse\x12\x30\n\rAppendEntries\x12\x0e.AppendRequest\x1a\x0f.AppendResponse\x12&\n\tGetLeader\x12\x05.Void\x1a\x12.GetLeaderResponse\x12!\n\x07Suspend\x12\x0f.SuspendRequest\x1a\x05.Void\x12$\n\x06SetVal\x12\t.KeyValue\x1a\x0f.SetValResponse\x12\x1f\n\x06GetVal\x12\x04.Key\x1a\x0f.GetValResponseb\x06proto3')



_VOTEREQUEST = DESCRIPTOR.message_types_by_name['VoteRequest']
_VOTERESPONSE = DESCRIPTOR.message_types_by_name['VoteResponse']
_APPENDREQUEST = DESCRIPTOR.message_types_by_name['AppendRequest']
_APPENDRESPONSE = DESCRIPTOR.message_types_by_name['AppendResponse']
_VOID = DESCRIPTOR.message_types_by_name['Void']
_GETLEADERRESPONSE = DESCRIPTOR.message_types_by_name['GetLeaderResponse']
_SUSPENDREQUEST = DESCRIPTOR.message_types_by_name['SuspendRequest']
_KEY = DESCRIPTOR.message_types_by_name['Key']
_KEYVALUE = DESCRIPTOR.message_types_by_name['KeyValue']
_LOGENTRY = DESCRIPTOR.message_types_by_name['LogEntry']
_SETVALRESPONSE = DESCRIPTOR.message_types_by_name['SetValResponse']
_GETVALRESPONSE = DESCRIPTOR.message_types_by_name['GetValResponse']
VoteRequest = _reflection.GeneratedProtocolMessageType('VoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOTEREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:VoteRequest)
  })
_sym_db.RegisterMessage(VoteRequest)

VoteResponse = _reflection.GeneratedProtocolMessageType('VoteResponse', (_message.Message,), {
  'DESCRIPTOR' : _VOTERESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:VoteResponse)
  })
_sym_db.RegisterMessage(VoteResponse)

AppendRequest = _reflection.GeneratedProtocolMessageType('AppendRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPENDREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendRequest)
  })
_sym_db.RegisterMessage(AppendRequest)

AppendResponse = _reflection.GeneratedProtocolMessageType('AppendResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPENDRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendResponse)
  })
_sym_db.RegisterMessage(AppendResponse)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  })
_sym_db.RegisterMessage(Void)

GetLeaderResponse = _reflection.GeneratedProtocolMessageType('GetLeaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLEADERRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:GetLeaderResponse)
  })
_sym_db.RegisterMessage(GetLeaderResponse)

SuspendRequest = _reflection.GeneratedProtocolMessageType('SuspendRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUSPENDREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:SuspendRequest)
  })
_sym_db.RegisterMessage(SuspendRequest)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:Key)
  })
_sym_db.RegisterMessage(Key)

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:KeyValue)
  })
_sym_db.RegisterMessage(KeyValue)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)

SetValResponse = _reflection.GeneratedProtocolMessageType('SetValResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETVALRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:SetValResponse)
  })
_sym_db.RegisterMessage(SetValResponse)

GetValResponse = _reflection.GeneratedProtocolMessageType('GetValResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETVALRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:GetValResponse)
  })
_sym_db.RegisterMessage(GetValResponse)

_RAFTELECTIONSERVICE = DESCRIPTOR.services_by_name['RaftElectionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTEREQUEST._serialized_start=14
  _VOTEREQUEST._serialized_end=114
  _VOTERESPONSE._serialized_start=116
  _VOTERESPONSE._serialized_end=160
  _APPENDREQUEST._serialized_start=163
  _APPENDREQUEST._serialized_end=314
  _APPENDRESPONSE._serialized_start=316
  _APPENDRESPONSE._serialized_end=363
  _VOID._serialized_start=365
  _VOID._serialized_end=371
  _GETLEADERRESPONSE._serialized_start=373
  _GETLEADERRESPONSE._serialized_end=429
  _SUSPENDREQUEST._serialized_start=431
  _SUSPENDREQUEST._serialized_end=463
  _KEY._serialized_start=465
  _KEY._serialized_end=483
  _KEYVALUE._serialized_start=485
  _KEYVALUE._serialized_end=523
  _LOGENTRY._serialized_start=525
  _LOGENTRY._serialized_end=578
  _SETVALRESPONSE._serialized_start=580
  _SETVALRESPONSE._serialized_end=613
  _GETVALRESPONSE._serialized_start=615
  _GETVALRESPONSE._serialized_end=663
  _RAFTELECTIONSERVICE._serialized_start=666
  _RAFTELECTIONSERVICE._serialized_end=927
# @@protoc_insertion_point(module_scope)
